version: '3'

networks:
  nuxt-network:
    driver: bridge
  default:


volumes:
  public-storage:
  node_modules: {}

services:
  receipt_frontend:
    build:
      dockerfile: ../docker/nuxt/Dockerfile
      context: './../frontend'
      args:
        - BASE_URL=https://https://proverka-cheka.ru/
        - API_URL=https://https://proverka-cheka.ru//api
    image: nginx:latest
    environment:
      - HOST=0.0.0.0
      - PORT=5001
    restart: "unless-stopped"
    ports:
      - "24678:24678"
      - '5001:80'
      - '445:443'
    networks:
      - nuxt-network
      - default
