version: '3'

networks:
  nuxt-network:
    driver: bridge
  default:


volumes:
  public-storage:
  node_modules: {}

services:
  receipt_frontend:
    build:
      dockerfile: ../docker/nuxt/Dockerfile
      context: './../frontend'
      args:
        - BASE_URL=https://proverka-cheka.ru/
        - API_URL=https://proverka-cheka.ru/api
    image: nginx:latest
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    restart: "no"
    ports:
      - "24681:24678"
      - "5001:3000"
    networks:
      - nuxt-network
      - default